from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse

from models import TextInput, TicketData, ChangeRequest, SelectedTickets, CreateSingleTicket
from ai_service import generate_ticket_from_text, apply_changes_to_ticket, extract_tickets_from_document
from jira_service import create_jira_ticket
from document_parser import parse_document

import os

app = FastAPI(title="Jira AI Bot", version="1.0.0")

# Allow frontend to call backend (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve frontend static files
frontend_path = os.path.join(os.path.dirname(__file__), "..", "frontend")
app.mount("/static", StaticFiles(directory=os.path.join(frontend_path, "static")), name="static")


@app.get("/")
def serve_frontend():
    """Serve the chatbot UI."""
    return FileResponse(os.path.join(frontend_path, "index.html"))


# ── Endpoint 1: Generate ticket from free text ──────────────────────────────
@app.post("/generate-ticket")
async def generate_ticket(payload: TextInput):
    """
    User types a description in plain English or a greeting.
    Returns a polite greeting response or a full ticket preview generated by GPT-4o-mini.
    """
    if not payload.user_text.strip():
        raise HTTPException(status_code=400, detail="Input text cannot be empty.")
    try:
        result = generate_ticket_from_text(payload.user_text)
        return {
            "success": True,
            "is_greeting": result.get("is_greeting", False),
            "greeting_message": result.get("greeting_message", ""),
            "is_multi_ticket": result.get("is_multi_ticket", False),
            "ticket": result.get("ticket"),
            "tickets": result.get("tickets")
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"AI generation failed: {str(e)}")


# ── Endpoint 2: Apply user changes to ticket preview ────────────────────────
@app.post("/update-preview")
async def update_preview(payload: ChangeRequest):
    """
    User says what they want to change in the preview.
    Returns updated ticket with changes applied.
    """
    if not payload.feedback.strip():
        raise HTTPException(status_code=400, detail="Feedback cannot be empty.")
    try:
        updated = apply_changes_to_ticket(payload.current_ticket.dict(), payload.feedback)
        return {"success": True, "ticket": updated}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Update failed: {str(e)}")


# ── Endpoint 3: Create single confirmed ticket in Jira ──────────────────────
@app.post("/create-ticket")
async def create_ticket(payload: CreateSingleTicket):
    """
    User confirmed the ticket preview.
    Creates the ticket in Jira and returns ticket ID and status.
    """
    try:
        result = create_jira_ticket(payload.ticket.dict())
        return {"success": True, "result": result}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Jira ticket creation failed: {str(e)}")


# ── Endpoint 4: Upload document and extract tickets ─────────────────────────
@app.post("/upload-document")
async def upload_document(file: UploadFile = File(...)):
    """
    User uploads a PDF, DOCX, or TXT file.
    AI reads the document and returns a list of all tickets found.
    User will then select which ones to create.
    """
    allowed_types = [".pdf", ".docx", ".txt"]
    filename = file.filename or ""
    ext = os.path.splitext(filename)[1].lower()

    if ext not in allowed_types:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{ext}'. Please upload PDF, DOCX, or TXT."
        )

    try:
        file_bytes = await file.read()

        # Step 1: Extract text from document
        document_text = parse_document(filename, file_bytes)

        if not document_text.strip():
            raise HTTPException(status_code=400, detail="The document appears to be empty.")

        # Step 2: AI reads document and extracts multiple tickets
        tickets = extract_tickets_from_document(document_text)

        if not tickets:
            raise HTTPException(status_code=400, detail="No tasks or tickets found in this document.")

        return {"success": True, "tickets": tickets, "count": len(tickets)}

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Document processing failed: {str(e)}")


# ── Endpoint 5: Create multiple selected tickets in Jira ─────────────────────
@app.post("/create-selected-tickets")
async def create_selected_tickets(payload: SelectedTickets):
    """
    User selected which tickets to create from the document list.
    Creates all selected tickets in Jira one by one.
    Returns results for each ticket.
    """
    # 1. Sort tickets by hierarchy level to ensure parents are created first
    # Hierarchy: Epic (0) -> Story/Task (1) -> Subtask (2)
    def get_level(t):
        it = t.issue_type.lower()
        if it == "epic": return 0
        if it == "subtask": return 2
        return 1
    
    sorted_tickets = sorted(payload.tickets, key=get_level)
    
    results = []
    id_map = {} # Maps temp_id -> actual Jira Key
    
    for ticket_data in sorted_tickets:
        ticket_dict = ticket_data.dict()
        
        # 2. If this ticket has a temp_parent_id, link it to the actual Jira Key of the parent
        temp_parent = ticket_dict.get("temp_parent_id")
        if temp_parent and temp_parent in id_map:
            actual_parent_key = id_map[temp_parent]
            # Determine if it should be epic_link or parent_task based on issue_type
            # But jira_service.py's create_jira_ticket handles both via 'parent' field logic
            # So we can just set one of them
            if ticket_dict.get("issue_type", "").lower() == "subtask":
                ticket_dict["parent_task"] = actual_parent_key
            else:
                ticket_dict["epic_link"] = actual_parent_key
        
        try:
            result = create_jira_ticket(ticket_dict)
            results.append({"success": True, "result": result})
            
            # 3. Store the mapping for children
            temp_id = ticket_dict.get("temp_id")
            if temp_id:
                id_map[temp_id] = result["ticket_id"]
                
        except Exception as e:
            results.append({"success": False, "error": str(e), "summary": ticket_data.summary})

    created = sum(1 for r in results if r["success"])
    failed  = len(results) - created

    return {
        "success": True,
        "results": results,
        "created": created,
        "failed":  failed,
    }


# ── Health check ─────────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return {"status": "ok", "service": "Jira AI Bot"}